### ISSUE TITLE
Arbitrary Values?

### ISSUE THREAD

**Issue by christianmagill** [dgknca/tailwindcss-container-query#1]
Looks like I was looking for Tailwind container queries just as this project was posted. 

All seems to working well!

I'm wondering if it might be possible to implement arbitrary values. To be honest, I'm not even sure if Tailwind supports this for plugins or not.

Much thanks

**Comment by dgknca** [comment]
Hi @christianmagill. I'm so glad it helped. You are talking about something like `.cq-w-[300px]:text-xl` right? It's exactly what I want to add. I have no idea how can I do that (I don't know if it's possible for variants) but I'll investigate it ASAP.

**Comment by christianmagill** [comment]
Yep, that's exactly what I'm talking about!

**Comment by ihscmagill** [comment]
@dgknca Ran across this Tweet and example that explains how to use arbitrary values. 

https://twitter.com/davidwebca/status/1468802754286080004/photo/1

https://play.tailwindcss.com/t4sKoCrxNo

**Comment by dgknca** [comment]
> @dgknca Ran across this Tweet and example that explains how to use arbitrary values.
> 
> https://twitter.com/davidwebca/status/1468802754286080004/photo/1
> 
> https://play.tailwindcss.com/SLtXEpJPbJ

It is a very different idea. I have to replace the variant with utilities. I'm not sure about using it because it has an unusual syntax. But looks like the only way for now. Thank you so much!

**Comment by dgknca** [comment]
P.S. it's not needed to use this plugin, you can just put these lines to your config directly:

```js
const plugin = require('tailwindcss/plugin')

module.exports = {
  ....
  plugins: [
    plugin(function({ matchVariant }) {
      matchVariant({
        'cq-h': (value) => `@container (min-height: ${value})`,
        'cq-w': (value) => `@container (min-width: ${value})`,
      })
    }),
  ]
}
```
