### ISSUE TITLE
polyfill errors saying "Failed to execute 'querySelectorAll' on 'Document'"

### ISSUE THREAD

**Issue by Enebz** [dgknca/tailwindcss-container-query#10]
I am trying to use your plugin for my Tailwind project, but I am getting these errors in the console.
![image](https://user-images.githubusercontent.com/46542339/161037052-899f21d9-4d0e-4b98-8cb7-a54178f2877d.png)
I suspect that the error is throw because the container is being used within a @media tag.
I don't see where I am using it under a media tag, because I am only using TailwindCSS.

**Comment by dgknca** [comment]
it's a [container-query-polyfill](https://github.com/GoogleChromeLabs/container-query-polyfill) error and you can see the same error here https://github.com/GoogleChromeLabs/container-query-polyfill/issues/23. it's not related to my plugin at all. you should open the issue in their repo.

**Comment by dgknca** [comment]
and I've never encountered this problem before. you can take a look at the [examples](https://github.com/dgknca/tailwindcss-container-query/tree/master/examples) folder to see how I use it with React and pure HTML projects.

**Comment by dgknca** [comment]
...and another issue complaining about the same issue https://github.com/GoogleChromeLabs/container-query-polyfill/issues/32
