### ISSUE TITLE
Document.querySelectorAll: '@media (min-width: 375px) ' is not a valid selector

### ISSUE THREAD

**Issue by RodrigoTomeES** [dgknca/tailwindcss-container-query#12]
Hi,

I am using the last version of the polyfill, v.0.1.2, and the last version of this plugin v.1.0.1 and I am getting the error -> Document.querySelectorAll: 'https://github.com/media (min-width: 375px) ' is not a valid selector

![imagen](https://user-images.githubusercontent.com/13077343/166210487-4f38d98f-ba0b-449d-8135-a1e751fe9c6b.png)

![imagen](https://user-images.githubusercontent.com/13077343/166211153-5e171e11-b41b-4c45-9988-f07aebe5d6a1.png)

I am using React v17.0.2, NextJS 12.1.0 and Tailwind 3.0.17 with PostCSS.

I add the import in useEffect inside the _app file,

Anyone has the same error?

Thanks

**Comment by dgknca** [comment]
Hi. It's related to the polyfill. The same issue here https://github.com/dgknca/tailwindcss-container-query/issues/10 and says he found a solution https://github.com/GoogleChromeLabs/container-query-polyfill/issues/32#issuecomment-1087462672

**Comment by RodrigoTomeES** [comment]
Thanks! @dgknca

**Comment by RodrigoTomeES** [comment]
@dgknca hi, I fixed the error but the classes doesn't work, it is as if PostCSS or Tailwind are removing the CSS that contains @container. Do you know that error? Thanks!

**Comment by dgknca** [comment]
Can you provide an example repo that reproduces your error?
