### ISSUE TITLE
Modifiers including `container-name` don't work

### ISSUE THREAD

**Issue by kafkas** [dgknca/tailwindcss-container-query#6]
Hey @dgknca, Thanks for the plugin! It works fine but can't seem to get it to work with the `container-name` specific modifiers. I'm assuming the readme fix in #5 is correct. My setup looks like this:

```html
<div class="... container-type-size container-name-lf">
  <div class="... cq-w-lf-xl:bg-blue-300" />
</div>
```
```ts
// tailwind.config.js
  theme: {
    containerName: {
      lf: 'layoutframe',
      // ...
    },
    containerQuery: {
      // ...
      lg: '480px',
      xl: '540px'
    },
  }
```
According to vscode intellisense, the raw CSS produced by the above setup is correct but the modifier doesn't seem to work. This one does work though: `cq-w-xl:bg-blue-300`. Any idea what might be the issue?

**Comment by dgknca** [comment]
hey, @kafkas thanks a lot for your contribution! My bad. Fixed in https://github.com/dgknca/tailwindcss-container-query/commit/33be651c4db5eafa992bf4f8ae514df2dd829a05 and released `1.0.1`. It was producing a wrong class name inside `@container name { }`.  Although we used `.cq-w-lf-xl`, `.cq-w-xl` was being generated in the query.

This now works as expected:

```
<div class="container-type-size container-name-lf w-80 h-80 overflow-auto resize">
  <div class="bg-yellow-100 h-full w-full border-4 border-gray-100 cq-w-lf-xl:bg-blue-200 cq-h-22:border-red-400 flex justify-end items-end">
    <div class="inline-flex items-end">
      <div class="pb-12">Resize the container</div>
      <svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="48" height="48" fill="white" fill-opacity="0.01"/><path d="M37 19V37H19" stroke="#333" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/><path d="M11.5441 11.5442L36.9999 37" stroke="#333" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
    </div>
  </div>
</div>
```

**Comment by kafkas** [comment]
Amazing, 1.0.1 works great. Thanks!

**Comment by dsldsl** [comment]
@dgknca I'm learning how to use this and have a q for you on the syntax you used.

Why do you use `cq-w-lf-xl:bg-blue-200` (with "lf") but then `cq-h-22:border-red-400` (without "lf")?  Thank you.
