### ISSUE TITLE
tailwindcss-container-query && Nextjs 

### ISSUE THREAD

**Issue by elBatel** [dgknca/tailwindcss-container-query#8]
Hi, the plugin is really cool and adopts the concept of tailwind, I really liked it
I have been trying for hours to add it to my project but I failed to do so
  I encountered many errors installing Container Query Polyfill in the project
That's why the plugin didn't work for me
Is there a guide for the steps to add to a project next or react ?

**Comment by dgknca** [comment]
Hi! Added a Nextjs example in [`/examples`](https://github.com/dgknca/tailwindcss-container-query/tree/master/examples) folder. I hope it helps you.

**Comment by elBatel** [comment]
Hi! , It's exactly what I was looking for it worked for me Thank you very much
I just have a question
Why did you use a layer of " tailwindcss/nesting" for what exact ?

**Comment by dgknca** [comment]
it's not needed for this case. but lets you to use nested selectors in `.css` files. like:

```css
.hero {
  &__title {
    @apply text-xl;
  }
}
```
